// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUBeDv153tavmLXzxuIPJf2Q-mrZkYceE',
    appId: '1:200951152227:ios:7ac8acf51f925354358256',
    messagingSenderId: '200951152227',
    projectId: 'fooddelivery-6b19d',
    storageBucket: 'fooddelivery-6b19d.appspot.com',
    iosBundleId: 'com.example.delivery',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPVee9KNla3C5JRHMcNPRQcfNv7-Z-N2Q',
    appId: '1:200951152227:web:935f3b7c63f9914c358256',
    messagingSenderId: '200951152227',
    projectId: 'fooddelivery-6b19d',
    authDomain: 'fooddelivery-6b19d.firebaseapp.com',
    storageBucket: 'fooddelivery-6b19d.appspot.com',
    measurementId: 'G-BFCJXZ2PLF',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUBeDv153tavmLXzxuIPJf2Q-mrZkYceE',
    appId: '1:200951152227:ios:7ac8acf51f925354358256',
    messagingSenderId: '200951152227',
    projectId: 'fooddelivery-6b19d',
    storageBucket: 'fooddelivery-6b19d.appspot.com',
    iosBundleId: 'com.example.delivery',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuKAz8uHGL8Mzf2v0_QoywNzgndmDrGxs',
    appId: '1:200951152227:android:e1cd7cc01b29ae89358256',
    messagingSenderId: '200951152227',
    projectId: 'fooddelivery-6b19d',
    storageBucket: 'fooddelivery-6b19d.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPVee9KNla3C5JRHMcNPRQcfNv7-Z-N2Q',
    appId: '1:200951152227:web:8923c9fca635ac75358256',
    messagingSenderId: '200951152227',
    projectId: 'fooddelivery-6b19d',
    authDomain: 'fooddelivery-6b19d.firebaseapp.com',
    storageBucket: 'fooddelivery-6b19d.appspot.com',
    measurementId: 'G-8VBQ1XFS84',
  );

}